version: "3.8"

services:
  postgresql:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_DB=maindb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  redis:
    image: 'redis:7.0.12-alpine'
    ports: 
      - 6379:6379    

  app:
   build: .
   entrypoint: [ "java", "-jar", "-Dspring.profiles.active=compose", "app.jar" ]
   ports:
      - 8080:8080
   depends_on: 
      - postgresql
      - redis
      
volumes:
  pg_data:
