services:
  mongodb:
    image: 'mongo:7.0.2'
    environment:
      - 'MONGO_INITDB_DATABASE=maindb'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - 27017:27017
