apiVersion: apps/v1

kind: Deployment
metadata:
  name: spotit-postgres
spec:
  selector:
    matchLabels:
      app: spotit-postgres
  template:
    metadata:
      labels:
        app: spotit-postgres
    spec:
      containers:
        - name: spotit-postgres
          image: postgres:15.4-alpine
          resources:
            limits:
              memory: '1Gi'
              cpu: '1000m'
          volumeMounts:
            - name: spotit-postgres-storage
              mountPath: /var/lib/postgres/data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: spotit-config
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spotit-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
      volumes:
        - name: spotit-postgres-storage
          persistentVolumeClaim:
            claimName: spotit-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spotit-postgres
spec:
  selector:
    app: spotit-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spotit-postgres-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotit-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
