name: "Test backend"

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./backend"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      
      - name: "Run tests and build"
        run: mvn -B package --file pom.xml

      - name: "Generate JaCoCo badge"
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          jacoco-csv-file: backend/target/site/jacoco/jacoco.csv
          fail-if-coverage-less-than: 80
      